// <auto-generated />
namespace OxfordStreet_online_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modelchangesv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelchangesv3));
        
        string IMigrationMetadata.Id
        {
            get { return "201908091927253_model-changes-v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
