// <auto-generated />
namespace OxfordStreet_online_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modelchangesv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelchangesv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201905301458124_model-changes-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
