// <auto-generated />
namespace OxfordStreet_online_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_product_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_product_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051525362_add_product_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
